image: node:latest
stages: ["build", "test", "deploy"]

# WARNING
# This pipeline needs the following variables set up to work:
# SERVER_IP =  // the ec2 instance public ip or domain
# SECRET_KEY = // the key to connect to the ec2 instance

# The cached folders between different pipeline jobs
cache:
  paths:
    - node_modules/

# the build job
build:
  stage: build
  script:
    - npm install

# the test job
test:
  stage: test
  script:
    - npm install
    - npm run test

# the deploy job
deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  image: python:latest
  script:
    - pip install awscli
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set region $AWS_DEFAULT_REGION
    - aws s3 cp build s3://renato-starwars/ --recursive --acl public-read


